---
name: R CMD check
'on':
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * MON'
jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - uses: r-lib/actions/setup-tinytex@v2
      - name: Install LaTeX packages
        run: |
          tlmgr install \
          parskip \
          geometry \
          koma-script \
          sectsty \
          titlesec \
          natbib \
          lastpage \
          hyperref
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libjpeg-dev \
            libpng-dev \
            libcairo2-dev
      - uses: uclahs-cds/tool-R-CMD-check-action@renv
        env:
          LANG: en_US.UTF-8
          LC_ALL: en_US.UTF-8
