---
name: R CMD check
'on':
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * MON'
jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-tinytex@v2
      - name: Install LaTeX packages
        run: |
          tlmgr install \
          parskip \
          geometry \
          koma-script \
          sectsty \
          titlesec \
          natbib \
          lastpage \
          hyperref
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libjpeg-dev \
            libpng-dev \
            libcairo2-dev \
            libv8-dev \
            libcurl4-openssl-dev
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::devtools
            any::rmarkdown
            any::V8
          needs: check
      - run: Rscript "${{github.action_path}}/install.github.R" --packages="${{github.event.inputs.github_dependencies}}" --token="${{github.event.inputs.token}}"
        shell: bash
      - uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--as-cran")'
          build_args: 'c("--compact-vignettes=gs+qpdf")'
      - name: Save built package and check results
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: check
