---
name: R-CMD-check (r-lib)
'on':
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - uses: r-lib/actions/setup-tinytex@v2
      - uses: uclahs-cds/tool-R-CMD-check-action@stable
