name: Unicode Graphics Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test-unicode:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install font packages
        run: |
          Rscript -e "install.packages(c('extrafont', 'systemfonts')"
      - name: Load fonts
        run: |
          Rscript -e "
            library(systemfonts)
            library(extrafont)
            dejavu_path <- systemfonts::match_fonts('DejaVu Sans')$path
            if (!is.na(dejavu_path)) {
              font_dir <- dirname(dejavu_path)
              extrafont::font_import(paths = font_dir, prompt = FALSE)
              extrafont::loadfonts(quiet = TRUE)
            } else {
              stop('DejaVu Sans not found')
            }
          "
      - name: Test R Unicode graphics
        run: |
          Rscript -e 'grid::grid.text("\u25CF")'
        env:
          LANG: en_US.UTF-8
          LC_ALL: en_US.UTF-8
