name: Unicode Graphics Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test-unicode:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Install system dependencies
        run: |
          sudo apt-get install -y libfontconfig1-dev
      - name: Install font packages
        run: |
          Rscript -e "install.packages(c('extrafont', 'systemfonts'))"
      - name: Test unicode character
        run: |
          Rscript -e "
            library(extrafont)
            library(systemfonts)
            dejavu_paths <- unique(na.omit(systemfonts::match_fonts('DejaVu Sans')\$path))
            if (length(dejavu_paths) == 0) stop('DejaVu Sans not found')
            font_dirs <- dirname(dejavu_paths)
            extrafont::font_import(paths = font_dirs, prompt = FALSE)
            extrafont::loadfonts(quiet = TRUE)
            for (font in pdfFonts()) {
                print(font$family)
                }
            options(bitmapType = 'cairo')
            grid::grid.text('\u25CF')"
        env:
          LANG: en_US.UTF-8
          LC_ALL: en_US.UTF-8
