name: Unicode Graphics Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  test-unicode:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Install font packages
        run: |
          Rscript -e 'install.packages(c('extrafont', 'systemfonts'))'
      - name: Test R Unicode graphics
        run: |
            Rscript -e 'grid::grid.text("\u25CF")'
        env:
          LANG: en_US.UTF-8
          LC_ALL: en_US.UTF-8
